version: '3.4'

services:
  coffeemachine.web:
    image: ${DOCKER_REGISTRY-}coffeemachineweb
    ports: 
        - 0.0.0.0:8081:443
    build:
      context: .
      dockerfile: src/CoffeeMachine.Web/Dockerfile
    links: 
        - postgres

  postgres: 
    image: postgres:14.2-alpine
    environment:
        POSTGRES_DB: "CoffeeMachine"
        POSTGRES_USER: "user"
        POSTGRES_PASSWORD: "qwe123"
    ports:
        - "5432:5432"
