version: '3.4'

services:
  coffeemachine.web:
    restart: on-failure:10
    image: ${DOCKER_REGISTRY-}coffeemachineweb
    ports: 
        - 8099:8099
    container_name: coffeeMachineWeb
    build:
      context: .
      dockerfile: src/CoffeeMachine.Web/Dockerfile
    links:
        - jenkins
        - postgres

  postgres: 
    restart: on-failure:10
    image: postgres:14.2-alpine
    environment:
        POSTGRES_DB: "CoffeeMachine"
        POSTGRES_USER: "user"
        POSTGRES_PASSWORD: "qwe123"
    ports:
        - 5432:5432
    container_name: postgres
    links:
        - jenkins

  jenkins: 
    restart: on-failure:10
    image: jenkins/jenkins:lts-alpine
    container_name: jenkins
    privileged: true
    user: root
    ports:
        - 0.0.0.0:8080:8080
    volumes:
        - ~/jenkins_home:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/local/bin/docker:/usr/local/bin/docker
    
