version: '3.4'

services:
  coffeemachine.web:
    restart: on-failure:10
    image: ${DOCKER_REGISTRY-}coffeemachineweb
    ports: 
        - 8099:8099
    container_name: coffeeMachineWeb
    build:
      context: .
      dockerfile: src/CoffeeMachine.Web/Dockerfile
    links:
        - postgres

  postgres: 
    restart: on-failure:10
    image: postgres:14.2-alpine
    environment:
        POSTGRES_DB: "CoffeeMachine"
        POSTGRES_USER: "user"
        POSTGRES_PASSWORD: "qwe123"
    ports:
        - 5432:5432
    container_name: postgres
    
